default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: launch_app_development

test:
  <<: *default
  database: launch_app_test

production:
  <<: *default
  database: launch_app_production
  username: launch_app
  password: <%= ENV["LAUNCH_APP_DATABASE_PASSWORD"] %>
